apiVersion: source.toolkit.fluxcd.io/v1beta1 # bedanya dengan helm biasa, version ini kita menggunakan flux
kind: HelmRepository
metadata:
  name: grafana
spec:
  interval: 1m0s
  url: https://grafana.github.io/helm-charts # kita menggunakan helm chart yang sudah ada
