apiVersion: apps/v1
kind: Deployment
metadata:
  name: finance
spec:
  selector:
    matchLabels:
      app: finance
  template:
    metadata:
      labels:
        app: finance
    spec:
      containers:
      - name: finance
        image: rizkyperdana28/nodejs-env:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
        envFrom:
          - secretRef:
              name: finance-secret
