apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studidevsecops5-ingress
  labels:
    name: studidevsecops5-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: studidevsecops.learn.me
    http:
      paths:
      - pathType: Prefix
        path: "/cores/nodejs-web"
        backend:
          service:
            name: nodejs-web-service
            port: 
              number: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-web-service
spec:
  type: ExternalName
  externalName: nodejs-web-service.cores.svc

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: studidevsecops5-ingress-2
  labels:
    name: studidevsecops5-ingress-2
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: studidevsecops.learn.me
    http:
      paths:
      - pathType: Prefix
        path: "/cores/nodejs-web-2"
        backend:
          service:
            name: nodejs-web-service-2
            port: 
              number: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-web-service-2
spec:
  type: ExternalName
  externalName: nodejs-web-service-2.cores.svc
