apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-web-app
spec:
  selector:
    matchLabels:
      app: nodejs-web-app
  template:
    metadata:
      labels:
        app: nodejs-web-app
    spec:
      containers:
      - name: nodejs-web-app
        image: gcr.io/striking-optics-378307/nodejs-web:1
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
      imagePullSecrets:
        - name: gcr-credentials
