apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: service-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ./helm/application # memanggil helm chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  values:
    images: nginx:latest
    port: 80